# Configuración Reactiva de PostgreSQL (Puerto 5432 según tu docker-compose)
quarkus.datasource.db-kind=postgresql
quarkus.datasource.reactive.url=postgresql://localhost:5432/auth_db
quarkus.datasource.username=auth_user
quarkus.datasource.password=auth_password

# Hibernate ORM (Generación automática de tablas para desarrollo)
quarkus.hibernate-orm.database.generation=update
